-- 코드를 입력하세요
SELECT
T1.PRODUCT_ID AS PRODUCT_ID,
T1.PRODUCT_NAME AS PRODUCT_NAME,
SUM(T1.PRICE * T2.AMOUNT) AS TOTAL_SALES
FROM
FOOD_PRODUCT T1
JOIN FOOD_ORDER T2 ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE
YEAR(T2.PRODUCE_DATE) = 2022 AND MONTH(T2.PRODUCE_DATE) = 5
GROUP BY T1.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, T1.PRODUCT_ID ASC