-- 코드를 작성해주세요
SELECT DISTINCT
T1.ID
, T1.EMAIL
, T1.FIRST_NAME
, T1.LAST_NAME
FROM
DEVELOPERS T1
JOIN
SKILLCODES T2
ON T2.NAME IN ('C#', 'Python')
AND T1.SKILL_CODE & T2.CODE = T2.CODE
ORDER BY T1.ID ASC