SELECT
  T1.YEAR,
  T2.MAX_SIZE - T1.SIZE_OF_COLONY AS YEAR_DEV,
  T1.ID
FROM (
  SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    SIZE_OF_COLONY,
    ID
  FROM ECOLI_DATA
) T1
JOIN (
  SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTIATION_DATE)
) T2 ON T1.YEAR = T2.YEAR
ORDER BY YEAR, YEAR_DEV