# -- 코드를 입력하세요
# SELECT
# DISTINCT(H.CAR_ID)
# FROM
# CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# RIGHT JOIN
# (
#     SELECT
#     CAR_ID
#     FROM
#     CAR_RENTAL_COMPANY_CAR
#     WHERE
#     CAR_TYPE = '세단'
# ) AS C ON C.CAR_ID = H.CAR_ID
# WHERE START_DATE LIKE '2022-10-%'
# ORDER BY CAR_ID DESC

SELECT
DISTINCT(B.CAR_ID)
FROM
CAR_RENTAL_COMPANY_RENTAL_HISTORY B
RIGHT JOIN (
    SELECT
    DISTINCT(CAR_ID)
    FROM
    CAR_RENTAL_COMPANY_CAR 
    WHERE
    CAR_TYPE = '세단'
) A ON A.CAR_ID = B.CAR_ID
WHERE B.START_DATE >= '2022-10-01'
ORDER BY B.CAR_ID desc