SELECT
T4.ID
, T3.FISH_NAME
, T3.LENGTH
FROM
FISH_INFO T4
JOIN
(
    SELECT
    T1.FISH_TYPE
    , T1.FISH_NAME
    , T2.LENGTH
    FROM 
    FISH_NAME_INFO T1
    JOIN (
        SELECT
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
        FROM
        FISH_INFO
        WHERE LENGTH IS NOT NULL
        GROUP BY FISH_TYPE
    ) T2 ON T1.FISH_TYPE = T2.FISH_TYPE
) T3 ON T4.FISH_TYPE = T3.FISH_TYPE AND T4.LENGTH = T3.LENGTH