SELECT
T1.CATEGORY,
SUM(T2.SALES) AS TOTAL_SALES
FROM
BOOK T1
JOIN (
    SELECT
    BOOK_ID,
    SALES
    FROM
    BOOK_SALES
    WHERE
    SALES_DATE LIKE ('2022-01%')
) T2 ON T1.BOOK_ID = T2.BOOK_ID
GROUP BY T1.CATEGORY
ORDER BY T1.CATEGORY ASC