-- 코드를 입력하세요
SELECT
T2.CATEGORY,
T2.MAX_PRICE,
T1.PRODUCT_NAME
FROM
FOOD_PRODUCT T1
JOIN (
    SELECT
    CATEGORY, 
    MAX(PRICE) AS MAX_PRICE
    FROM
    FOOD_PRODUCT
    GROUP BY CATEGORY
) T2 ON T1.CATEGORY = T2.CATEGORY AND T1.PRICE = T2.MAX_PRICE
WHERE
T2.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY T2.CATEGORY
ORDER BY T2.MAX_PRICE DESC