-- 코드를 입력하세요
SELECT
BOOK_ID
, AUTHOR_NAME
, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM
BOOK T1
JOIN
AUTHOR T2 ON T1.author_id = T2.author_id
WHERE
CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC